timeout: 3

/Xinix
    protocol: limine
    path: boot():/boot/xinix-loader
    resolution: 1280x720x32

/Xinix But Bigger
    protocol: limine
    path: boot():/boot/xinix-loader
    resolution: 1920x1080x32

/Xinix But Even Bigger
    protocol: limine
    path: boot():/boot/xinix-loader
    resolution: 2560x1600x32
