#ifndef SYSRESULT_DEF_ERROR_CONSTANT
#error Cannot include this header directly. Include <sysresult.h> instead
#endif

// ERR_GENERIC = -1,
SYSRESULT_DEF_ERROR_CONSTANT(GENERIC, -1)

SYSRESULT_DEF_ERROR_CONSTANT(INSUFFICIENT_MEMORY, -2)

//     ERR_IMAGE_VALIDATION_ERROR = -32,
SYSRESULT_DEF_ERROR_CONSTANT(IMAGE_VALIDATION_ERROR, -32)
//     ERR_IMAGE_WX_SEG = -36,
SYSRESULT_DEF_ERROR_CONSTANT(IMAGE_WX_SEG, -36)
//     ERR_IMAGE_INVALID_RELOC = -37,
SYSRESULT_DEF_ERROR_CONSTANT(IMAGE_INVALID_RELOC, -37)

SYSRESULT_DEF_ERROR_CONSTANT(UNUSABLE_TSC, -38)
